### ISSUE TITLE
How do you install this?

### ISSUE THREAD

**Issue by Bahlinc-Dev** [mongodb/chatbot#273]
The following packages in `mongodb-chatbot-ui ` are not on npm:

```  
    "@lg-chat/avatar": "^2.0.6",
    "@lg-chat/chat-disclaimer": "^2.0.0",
    "@lg-chat/chat-window": "^1.0.4",
    "@lg-chat/fixed-chat-window": "^1.1.1",
    "@lg-chat/input-bar": "^3.2.6",
    "@lg-chat/leafygreen-chat-provider": "^1.0.2",
    "@lg-chat/message": "^2.0.8",
    "@lg-chat/message-feed": "^2.0.7",
    "@lg-chat/message-prompts": "^1.0.2",
    "@lg-chat/message-rating": "^1.1.3",
```

This results in auth errors during `npm install`

`.nprc `has these commented out lines:

```
//artifactory.corp.mongodb.com/artifactory/api/npm/leafygreen-ui/:_authToken=${LG_ARTIFACTORY_TOKEN}
//artifactory.corp.mongodb.com/artifactory/api/npm/leafygreen-ui/:email=${LG_ARTIFACTORY_EMAIL}
//artifactory.corp.mongodb.com/artifactory/api/npm/leafygreen-ui/:always-auth=true

//registry.npmjs.org/:_authToken=${MONGODB_EAI_NPM_TOKEN}
```

Do you need this, and if so where do you get these tokens??

**Comment by nlarew** [comment]
Hi @Bahlinc-Dev thanks for filing an issue!

As you've noticed, those `@lg-chat/*` packages are currently hosted on our private internal package repository and are not publicly available. We're working on moving them to npm but for now you won't be able to install them or develop the UI locally.

You _can_ use the chatbot UI components if you install the [package published on npm](https://www.npmjs.com/package/mongodb-chatbot-ui):

```shell
npm install mongodb-chatbot-ui
```
