### ISSUE TITLE
InputBarTrigger does not accept placeholder

### ISSUE THREAD

**Issue by eric-gardyn** [mongodb/chatbot#310]
doc refers to InputBarTrigger accepting a placeholder prop.
https://mongodb.github.io/chatbot/ui
But the latest version of the code does not.

**Comment by nlarew** [comment]
Hi Eric!

What version of the UI are you using? The documentation site currently reflects only the latest published version.

We added support for the `placeholder` prop in the `0.2.0+` releases so you should upgrade to the latest version. I just tested on `v0.2.1` and was able to get this minimal example working without a problem:

```typescript
import Chatbot, { InputBarTrigger } from "mongodb-chatbot-ui";
import './App.css'

function App() {
  return (
    <Chatbot serverBaseUrl="http://localhost:3000">
      <InputBarTrigger placeholder="Custom placeholder message!" />
    </Chatbot>
  );
}

export default App
```

<img width="871" alt="Screenshot 2024-01-30 at 3 57 39 PM" src="https://github.com/mongodb/chatbot/assets/15657698/f3ebf3a2-0bad-412b-81a3-48fa575c7df9">

**Comment by eric-gardyn** [comment]
thank you. I think my issue came from using the 'examples/quick-start' folder. somehow it didn't install the latest mongodb-chatbot-ui.
