### ISSUE TITLE
Chatbot stream error: Internal Server Error

### ISSUE THREAD

**Issue by beakae** [mongodb/chatbot#425]
When querying the chatbot with a specific conversation ID, the server returns a 500 error with the message: invalid parameter: expected an object (filter). The error seems to indicate that MongoDB is receiving an invalid filter object, possibly related to conversation IDs.

Error Message: Responding with 500 status and error message: invalid parameter: expected an object (filter).","reqId":"6658d5ec0e5299ff12a98251"}

Steps to reproduce:
1. Follow Quick Start steps in documentation
2. OR use the demo website https://cookbook-chat.onrender.com/ 

![issue](https://github.com/mongodb/chatbot/assets/122573839/3da3c437-82d8-4193-ba28-eb783400a346)

**Comment by jameslimjy** [comment]
im facing this issue too

**Comment by lukjaki** [comment]
Same for me

**Comment by nlarew** [comment]
Hi everyone, just letting you know that we're investigating what's going on here and hope to have a fix for you soon

**Comment by nlarew** [comment]
A fix for this issue is now live in the latest version of `mongodb-chatbot-server`:

```
npm install mongodb-chatbot-server@^0.9.1
```

**Comment by JohnGUnderwood** [comment]
I still see this issue even after upgrade

```
{"level":"info","message":"Server listening on port: 3000"}
{"level":"info","message":"Request for: /api/v1/conversations","reqId":"665f7733aef2fbe33385ec27"}
{"level":"info","message":"Request IP ::1 is allowed","reqId":"665f7733aef2fbe33385ec27"}
{"level":"info","message":"Request origin http://localhost:5173/ is allowed","reqId":"665f7733aef2fbe33385ec27"}
{"level":"info","message":"Creating conversation","reqId":"665f7733aef2fbe33385ec27"}
{"level":"info","message":"Responding with conversation 665f7733aef2fbe33385ec28","reqId":"665f7733aef2fbe33385ec27"}
{"level":"info","message":"Request for: /api/v1/conversations/665f7733aef2fbe33385ec28/messages?stream=true","reqId":"665f7734aef2fbe33385ec2a"}
{"level":"info","message":"Request IP ::1 is allowed","reqId":"665f7734aef2fbe33385ec2a"}
{"level":"info","message":"Request origin http://localhost:5173/ is allowed","reqId":"665f7734aef2fbe33385ec2a"}
{"level":"info","message":"Request info:\nUser message: Why should I use the MongoDB Chatbot Framework?\nStream: true\nIP: ::1\nConversationId: 665f7733aef2fbe33385ec28","reqId":"665f7734aef2fbe33385ec2a"}
{"level":"error","message":"Responding with 500 status and error message: invalid parameter: expected an object (filter).","reqId":"665f7734aef2fbe33385ec2a"}
```

**Comment by beakae** [comment]
Also still somewhat running into issues. The only version I had working was encountering the same:
Unfortunately, I do not know how to respond to your message.
Please try to rephrase your message. Adding more details can help me respond with a relevant answer.

**Comment by JohnGUnderwood** [comment]
`npm install --force` in the `examples/quick-start` directory seems to have fixed my issue.
