### ISSUE TITLE
  "error": "invalid parameter: expected an object (filter)"

### ISSUE THREAD

**Issue by lukewealth** [mongodb/chatbot#426]
Everything has been working fine for me but suddenly i start to get this error 
`{"level":"info","message":"Request info:\nUser message: what are vectors\nStream: true\nIP: ::1\nConversationId: 663fe16f4e7d858ab63c1e83","reqId":"66599a882ba207f3a014a906"}
{"level":"error","message":"Responding with 500 status and error message: invalid parameter: expected an object (filter).","reqId":"66599a882ba207f3a014a906"}`

I have tried debugging several methods. started the repo afresh and still yet i am getting this error

**Comment by mongodben** [comment]
thanks for bringing this to our attention and apologies for any inconvenience that this issue may have caused you.

this is the same issue as #425. 

we have investigated and have a fix in PR #427.

closing this issue. we will provide information about when the fix is live in #425.
