### ISSUE TITLE
Does not work with latest models

### ISSUE THREAD

**Issue by hasaketa** [mongodb/chatbot#441]
It does not produce response with text-embedding-3-small and gpt-4o combination

**Comment by mongodben** [comment]
can you provide more information about the error that you're getting so we can help debug? 

as a first step, you can try to lower the `minScore` in the `FindContentFunc`. the `.9` that we have as a default in the quick start works well for ada-02 but is often too high for `text-embedding-3-small`.

```ts
const findContent = makeDefaultFindContent({
  embedder,
  store: embeddedContentStore,
  findNearestNeighborsOptions: {
    k: 5,
    path: "embedding",
    indexName: VECTOR_SEARCH_INDEX_NAME,
    // Start low to make sure all is working, and work your way up to a higher score if it's suiting. 
    minScore: 0.1,
  },
});
```

**Comment by hasaketa** [comment]
Followed your suggestion to lower the minScore to 0.1 and that worked. Thank you!
