### ISSUE TITLE
How to Handle Requests with Base64 Image Data Using OpenAI's Advanced API like GPT-4 in This Framework?

### ISSUE THREAD

**Issue by beestudio3t** [mongodb/chatbot#443]
I am not yet sure how to handle requests when using OpenAI's advanced API, such as GPT-4, to generate responses in cases where the data sent in the request includes image data in base64 format within this framework. Please help me understand this process. Thank you.

**Comment by mongodben** [comment]
we do not currently support handling images. text only for now. sorry for the inconvenience. 

we don't have any plans at the moment to support non-text media formats, though in the future that may change.
