### ISSUE TITLE
Really great work!!! Love it.

### ISSUE THREAD

**Issue by artknight** [mongodb/chatbot#470]
Hey, sorry to post it here as I did not see any way to contact you. I run a daily newsletter for developer (https://dailysandbox.com) focussing on "coding with AI". I really like your work, so I am going to feature it in the tomorrow's issue.

**Comment by mongodben** [comment]
thanks! just saw the mention here https://dailysandbox.com/p/daily-digest-javascript-ai. we appreciate your support and spreading the word.

closing the PR.
