### ISSUE TITLE
makeUserMessage function response type

### ISSUE THREAD

**Issue by eric-gardyn** [mongodb/chatbot#476]
In quick-start/packages/server/src/index.ts,
makeUserMessage is defined as

```
const makeUserMessage: MakeUserMessageFunc = async function ({
  content,
  originalUserMessage,
}): Promise<OpenAiChatMessage & { role: 'user' }> {
```

it is used as an argument to
```
const generateUserPrompt: GenerateUserPromptFunc = makeRagGenerateUserPrompt({
  findContent,
  makeUserMessage,
})
```

with makeRagGenerateUserPrompt's params of type MakeRagGenerateUserPromptParams
with
```
    makeUserMessage: MakeUserMessageFunc;
```

and 
```
export type MakeUserMessageFunc = (params: MakeUserMessageFuncParams) => Promise<UserMessage>;
```

so, instead of the expected UserMessage type (which I think is the correct one), makeUserMessage function type signature wrongly uses OpenAiChatMessage & { role: 'user' }.

what do you think?

**Comment by mongodben** [comment]
i think you're correct that the typing in the quick start is misleading (though due to type overlap, i think both will compile). care to PR the fix? 😄

**Comment by eric-gardyn** [comment]
https://github.com/mongodb/chatbot/pull/477
